jjb: fix email_body definition
Remove last newline. It was causing:
> org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:
> WorkflowScript: 29: expecting ''', found '\n' @ line 29, column 201.
>    axLines=100, escapeHtml=false}
>                                  ^
>
> 1 error

Change-Id: Ic624109e81de362ee56a2b822cdbde6f01fe3284